name: Documentation

on:
  push:
    branches:
      - main
      - 'release-'
    tags: ['*']
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    uses: "SciML/.github/.github/workflows/documentation.yml@v1"
    secrets: "inherit"
